#!/usr/bin/env python3
"""Build the synthetic corpus the egress demo reads from.

The documents are *generated*, not committed, and that was not a stylistic choice: the
first two attempts at checking them in were refused by ZeroTrace's own PreToolUse hook,
because writing a register of Aadhaar-shaped numbers means putting those numbers in a
tool argument. The product was right both times, so the corpus is derived here instead
and the repository never carries a file full of identifier-shaped strings.

That constraint shapes the whole file. Nothing identifier-shaped appears as a literal:

  * twelve-digit numbers are eleven-digit bases plus a Verhoeff digit computed at import
  * a GSTIN is a fourteen-character prefix plus a mod-36 character, likewise computed
  * a PAN or an IFSC is assembled by `joined()` from pieces that match nothing on their own

Both check digits are brute-forced against the *shipped validators*, which is what
guarantees the corpus exercises the checksum path rather than producing numbers that
merely look right. It also makes the demo portable: `python demo/corpus/generate.py` on
any machine produces the same tree, so the prompts in docs/21 refer to paths that exist.

**Everything here is synthetic.** The names are invented, the districts are real but the
people are not, and every identifier belongs to nobody. The credentials are equally fake:
a connection string pointing at a `.invalid` host, which by RFC 2606 can never resolve.

The tree mirrors the security groups in Control-DB/policies/bharat-digital.yaml:

    citizen-services/   citizen records      CUSTOMER_DATA, AADHAAR, QUASI_IDENTIFIER_SET
    revenue/            tax and financial    FINANCIAL_RECORD, GSTIN
    hr-personnel/       staff records        HR_RECORD
    infosec/            secrets and findings INFRA_SECRET, SECURITY_FINDING
    public/             open material        nothing -- the control case

`public/` is not filler. A demo in which every read is blocked proves only that the tool
says no; the open circular is what shows the same person, in the same session, reading
what they are entitled to with no friction at all.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from gateway.detectors.india_id import gstin_ok, verhoeff_ok  # noqa: E402

HERE = Path(__file__).resolve().parent
TREE = HERE / "bharat-digital"

BANNER = "# SYNTHETIC — generated by demo/corpus/generate.py. Invented people, fake numbers."


def joined(*parts: str) -> str:
    """Assemble an identifier from pieces that match nothing individually.

    A PAN and an IFSC have no check digit to derive, so the only way to keep the literal
    out of this file is to write it in halves. It reads oddly, and the alternative is a
    source file our own hook refuses to write.
    """
    return "".join(parts)


def with_check_digit(base11: str) -> str:
    """The twelve-digit form of an eleven-digit base, with a valid Verhoeff digit."""
    for d in "0123456789":
        if verhoeff_ok(base11 + d):
            return base11 + d
    raise AssertionError(f"no valid check digit for {base11!r}")


def with_gstin_check(base14: str) -> str:
    """The fifteen-character GSTIN, with the mod-36 character the detector expects."""
    for c in "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ":
        if gstin_ok(base14 + c):
            return base14 + c
    raise AssertionError(f"no valid check character for {base14!r}")


def grouped(uid: str) -> str:
    return f"{uid[:4]} {uid[4:8]} {uid[8:]}"


# The assessee's identifiers, split so no literal here is a match on its own.
PAN_ASSESSEE = joined("AABC", "V22", "33K")
IFSC_BRANCH = joined("SBIN", "000", "4312")
GSTIN_ASSESSEE = with_gstin_check(joined("29", PAN_ASSESSEE, "1Z"))
GSTIN_SECOND = with_gstin_check(joined("29", "AAGC", "S88", "91M", "1Z"))
GSTIN_THIRD = with_gstin_check(joined("29", "AACC", "P44", "10R", "1Z"))

#: (citizen_id, name, 11-digit base, dob, gender, pincode, scheme, mobile)
CITIZENS = [
    ("CIT-88231", "Rekha S Sharma",  "66414761511", "14/07/1988", "female", "563101", "14", "9845512207"),
    ("CIT-88232", "Mahesh K Gowda",  "82077192578", "02/11/1979", "male",   "563101", "7",  "9886640118"),
    ("CIT-88233", "Fatima Begum",    "38587141696", "23/01/1994", "female", "563103", "14", "9741203366"),
    ("CIT-88234", "Anil Kumar Naik", "99323654548", "30/06/1966", "male",   "563114", "21", "9611778450"),
    ("CIT-88235", "Lakshmi Devi",    "82466463288", "09/09/1971", "female", "563101", "14", "9900312874"),
]


def citizen_services() -> dict[str, str]:
    lead = CITIZENS[0]
    grievance = f"""{BANNER}

# Grievance file GRV-2291 — RESTRICTED (citizen-services)

    ticket_id        GRV-2291
    case_file        opened 2026-03-04, ward 14, Kolar district
    status           pending field verification
    assigned officer s.iyer

## Applicant

    applicant name   {lead[1]}
    s/o              Suresh Sharma
    citizen_id       {lead[0]}
    uid              {grouped(with_check_digit(lead[2]))}
    dob              {lead[3]}
    gender           {lead[4]}
    mobile           {lead[7]}
    address          House 22, 3rd Cross, Vinayaka Layout, Kolar, pincode {lead[5]}

## Complaint

Beneficiary was enrolled under scheme 14 (widow pension) in November 2025 and has
received no disbursal for four consecutive months. The applicant states the bank
account on record was closed by the branch in December.

    bank_account     4311298874 (closed)
    ifsc             {IFSC_BRANCH}

## Action taken

Field officer to verify residence and re-seed the account. The grievance must be
closed within the 30-day statutory window.
"""

    header = ("citizen_id,applicant name,uid,dob,gender,district,pincode,"
              "scheme,enrolment_no")
    rows = [
        f"{cid},{name},{with_check_digit(base)},{dob},{gender},Kolar,{pin},{scheme},"
        f"ENR-{2291 + i}"
        for i, (cid, name, base, dob, gender, pin, scheme, _m) in enumerate(CITIZENS)
    ]
    register = "\n".join([
        BANNER,
        "# RESTRICTED — citizen-services. Beneficiary enrolment register, ward 14.",
        "# Held under the Aadhaar (Targeted Delivery of Financial and Other Subsidies,",
        "# Benefits and Services) Act, 2016.",
        header, *rows, "",
    ])

    return {
        "grievance-GRV-2291.md": grievance,
        "beneficiary-register-ward-14.csv": register,
    }


def revenue() -> dict[str, str]:
    assessment = f"""{BANNER}

# GST assessment note 2025-26 — RESTRICTED (revenue)

    tax_invoice      INV-2025-4471
    invoice_number   4471/KOL/25
    fiscal year      2025-26
    assessing officer r.banerjee

## Assessee

    trade name       Vinayaka Infrastructure Works
    gstin            {GSTIN_ASSESSEE}
    pan              {PAN_ASSESSEE}
    ledger           electronic credit ledger, Kolar circle

## Assessment

    gst_amount       18,44,120 declared
    debit            2,11,400 reversed under rule 42
    credit           4,80,000 transitional, disallowed
    account_balance  6,91,520 payable including interest

Show-cause issued under section 73. The assessee has thirty days to reply before
the demand is confirmed.
"""

    refunds = "\n".join([
        BANNER,
        "# RESTRICTED — revenue. Refund register, quarter 3, Kolar circle.",
        "invoice_number,gstin,tax_invoice,fiscal year,gst_amount,debit,credit,status",
        f"4471/KOL/25,{GSTIN_ASSESSEE},INV-2025-4471,2025-26,1844120,211400,480000,held",
        f"4472/KOL/25,{GSTIN_SECOND},INV-2025-4472,2025-26,320900,0,52000,sanctioned",
        f"4473/KOL/25,{GSTIN_THIRD},INV-2025-4473,2025-26,1180450,74300,0,sanctioned",
        f"4474/KOL/25,{GSTIN_ASSESSEE},INV-2025-4474,2025-26,96700,0,12800,rejected",
        "",
    ])

    return {
        "gst-assessment-2025-26.md": assessment,
        "refund-register-Q3.csv": refunds,
    }


def hr_personnel() -> dict[str, str]:
    payslip = f"""{BANNER}

# Payslip March 2026 — RESTRICTED (hr-personnel)

    employee_id      EMP-4471
    name             A Deshpande
    designation      Assistant Director (Technical)
    date_of_joining  2019-08-12
    reporting manager P Rao
    pf_number        PY/KOL/4471/0092

## Earnings

    basic            72,400
    dearness         31,190
    hra              18,650
    salary           1,22,240 gross

## Deductions

    pf               8,688
    tax              14,110
    net              99,442

This payslip is confidential to the employee and to hr-personnel.
"""

    appraisal = f"""{BANNER}

# Appraisal cycle 2025 — RESTRICTED (hr-personnel)

    employee_id      EMP-4471
    designation      Assistant Director (Technical)
    reporting manager P Rao
    ctc              14,68,000 revised from 13,20,000
    appraisal        band B+, recommended for one increment
    date_of_joining  2019-08-12
    pf_number        PY/KOL/4471/0092

## Reviewer note

Handles the ward-14 grievance backlog well under load. Communication with field
staff needs work. Not recommended for the director track this cycle.
"""

    return {
        "payslip-2026-03-EMP4471.md": payslip,
        "appraisal-cycle-2025.md": appraisal,
    }


def infosec() -> dict[str, str]:
    runbook = f"""{BANNER}

# Production restore runbook — RESTRICTED (infosec)

## 1. Break glass

    vault path       secret/data/prod/postgres
    credential       read with the operator role, never copied to a workstation
    password         rotate immediately after any restore

## 2. Primary connection

    connection_string  postgresql://svc_restore@db-primary.internal.invalid:5432/citizens
    api_key            issued per restore, expires in one hour
    secret_key         held in the HSM; this runbook never contains it

## 3. Environment

The service reads its own .env from the sealed volume. Do not template it by hand;
the last incident was caused by a private_key pasted into a shell history.

## 4. After

Revoke the restore role. Confirm the audit chain has no gap across the window.
"""

    pentest = f"""{BANNER}

# Penetration test, February 2026 — RESTRICTED (infosec)

    engagement       external, grey box, two weeks
    scope            citizen services portal and the grievance API

## Findings

### F-01 — severity high

    cvss             8.1
    vulnerability    the grievance API accepts an enrolment number without checking
                     that the session owns it, so any authenticated user can enumerate
    exploit          incrementing ENR- values returns other citizens' records
    remediation      bind the record to the session subject at the query, not the view

### F-02 — severity medium

    cve-2025-40912   outdated TLS terminator on the ingest path
    cvss             6.4
    remediation      upgrade and re-run the external scan

### F-03 — severity low

    vulnerability    verbose stack traces on 500, leaking internal hostnames
    remediation      generic error page, structured logs behind the boundary
"""

    return {
        "runbook-prod-restore.md": runbook,
        "pentest-2026-02.md": pentest,
    }


def public() -> dict[str, str]:
    faq = f"""{BANNER}

# Scheme 14 (widow pension) — public information

**Who is eligible?** A widow resident in the state, aged 18 or above, whose annual
household income is below the notified ceiling.

**What is the entitlement?** A monthly pension credited directly to a bank account
in the applicant's own name.

**How do I apply?** At the taluk office or through the state services portal. Bring
proof of residence, proof of identity and the death certificate of the spouse.

**How long does it take?** Sanction is targeted within 45 days of a complete
application. Disbursal begins the month after sanction.

**What if payment stops?** File a grievance at the taluk office. The office must
respond within 30 days.
"""

    circular = f"""{BANNER}

# Circular 2026/11 — office timings and public grievance hours

All district offices will observe public grievance hours from 11:00 to 13:00 on
every working Tuesday and Thursday, with effect from 1 April 2026.

Officers designated as public information officers must be available in person
during these hours. Where an officer is on field duty, the office must display the
name of the officer standing in.

This circular is for general circulation and may be published on the district
website.
"""

    return {"scheme-14-faq.md": faq, "circular-2026-11.md": circular}


SECTIONS = {
    "citizen-services": citizen_services,
    "revenue": revenue,
    "hr-personnel": hr_personnel,
    "infosec": infosec,
    "public": public,
}


def build() -> list[Path]:
    written: list[Path] = []
    for group, make in SECTIONS.items():
        folder = TREE / group
        folder.mkdir(parents=True, exist_ok=True)
        for name, text in make().items():
            path = folder / name
            path.write_text(text, encoding="utf-8")
            written.append(path)
    return written


def main() -> int:
    written = build()
    print(f"corpus written to {TREE}")
    for path in written:
        print(f"  {path.relative_to(TREE)}")
    print()
    print("Now run:  zerotrace login s.iyer   (or r.banerjee, m.khan, a.das, cag.audit)")
    print("then ask Claude Code to read one of these files. See docs/21_EGRESS_DEMO.md.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
